require: rubocop-rails

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - !ruby/regexp /old_and_unused\.rb$/

Style/FrozenStringLiteralComment:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/ClassAndModuleChildren:
  Enabled: false
Layout/LineLength:
  Max: 120
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Bundler/OrderedGems:
  Enabled: false
