require: rubocop-rails

Style/FrozenStringLiteralComment:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Layout/LineLength:
  Max: 120
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
